### PR TITLE
Windows Containers sample with Seq

### PR DESCRIPTION
**Pull request by skomis-mm**
- dockerized `Seq`
- updated web-sample that can also run on `NanoServer` with overridable logging settings via `Serilog.Settings.Configuration` package and environment variables
- new sample-windows.yml with updated `readme.md`

Tested on Windows Server 2016 (can be run in VM). Individual containers can run on Windows 10 Pro / Ent with Hyper-V as well, but `docker-compose` according to [this blog post](https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/) don't work in Windows 10 for now.

### CODE REVIEW

**Comment by merbla** [comment]
@skomis-mm LGTM.  I don't have a machine to test but great to get a windows story going.  @adamchester anything to add here?

**Comment by adamchester** [comment]
LGTM - I don't have a test machine for this yet either, but keen to try dockerised Seq :+1:

**Comment by merbla** [comment]
ping @nblumhardt re: Any licence issues with Seq in a container?

**Comment by nblumhardt** [comment]
Awesome! :+1: 

@merbla no, I don't think so. LGTM!

**Pull request merged**
